name: Renovate config validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/renovate-config-validator@v2
