name: Renovate config validation

on:
  push:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: tj-actions/renovate-config-validator@v2
